url: http://blog.byjean.eu
title: Byjean
subtitle: Scala, Javascript vs Craftsmanship
author: Jean Helou
subscribe_rss: /atom.xml

sass:
    #style: compressed
    sass_dir: _sass
paginate: 5          # Posts per page on the blog index
paginate_path: page/:num # Pagination dir settings
titlecase: true       # Converts page and post titles to titlecase
excerpt_separator: <!--more-->
excerpt_link: ...

kramdown:
  input: GFM
  syntax_highlighter: rouge


gems: [jekyll-paginate]
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: jeantil
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Mastodon
mastodon_ser: "@jhelou@mamot.fr"


