url: http://blog.byjean.eu
title: Byjean
subtitle: Scala, Javascript vs Craftsmanship
author: Jean Helou
subscribe_rss: /atom.xml

sass:
    #style: compressed
    sass_dir: _sass
paginate: 5          # Posts per page on the blog index
paginate_path: page/:num # Pagination dir settings
titlecase: true       # Converts page and post titles to titlecase
excerpt_separator: <!--more-->
excerpt_link: ...
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions:
    - fenced_code_blocks
    - strikethrough
    - autolink
    - footnotes
    - smart

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: jeantil
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: jeanhelou
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: byjean
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-41261061-1

# Facebook Like
facebook_like: false
